fix_styles = {'Figurative': ['Figuratif', 'Figurativo'],
            'Realism': ['Realistic Painting', 'Realismo', 'Painterly Realism', 'Realistic'],
            'Expressionism': ['Espressionismo', 'Expression', 'Expresionismo', 'Expresionism', 'Expressionisme', 'Expresionist'],
            'Color Field': ['Colorfield', 'Colourfield', 'Colour Field', 'Color Block Colorfield'],
            'Japanese': ['Japanese Painting', 'Japanese Art'],
            'Surrealism': ['Surrealisme', 'Surrealismo', 'Surreal', 'Modern Surrealism'],
            'Linear': ['Llinear'],
            'Mid Century': ['Midcentury Style', 'Mid Century Modern'],
            'Modernism': ['Mdoernist', 'Modernist', 'Moden', 'Modern'],
            'Dadaism': ['Dada', 'Neo Neo Dada'],
            'Minimalism': ['Minimalist', 'Minimal', 'Minimalismo', 'Postminimalism', 'Minimalismn'],
            'Geometric': ['Geometrico'],
            'Naive': ['Naif'],
            'Optical': ['Op Art', 'Arte Optico', 'Op'],
            'Post Impressionism': ['Postimprisionism', 'Postimpressionism'],
            'Informalism': ['Informalismo', '#Informal', 'Informal'],
            'Formism': ['Form'],
            'Black And White': ['Black White', 'Blackandwhite'],
            'Magical Realism': ['Magic Realism'],
            'Photorrealism': ['Hyperrealism', 'Photorrealist', 'Photorealism'],
            'Deconstructivism': ['Deconstructuvist'],
            'Pop': ['Pop´', 'Popart', 'Neopop'],
            'Calligraphy': ['Chinese  Calligraphy', 'Japanese Calligraphy', 'Caligrama', 'Lettrisme'],
            'Arte Povera': ['Arte Povere'],
            'Dot': ['Dots'],
            'Quilting': ['Quilt', 'Art Quilt'],
            'Abstract': ['Abstract Landscape', 'Abstract Cityscape'],
            'Post Impressionism': ['Postimpresionism', 'Surrealistic Impressionism']}

remove_styles = ['People', 'Spiritual', 'Female', 'landscape', 'Ink Brush', 'Studio'
                'Unique', 'Nude', 'No Style Really', 'Oil On Linen', '',
                'Wood', 'Melted Wax', 'Children Playing', 'Bellas Artes',
                'Portrait', 'My Own Style', 'Gabriele Luise Koch', 'Still Life',
                'Fine Art', 'Colorful Art', 'Tag', 'Party', 'Jackson Pollock',
                'Gaming', 'Romantic Style', 'Drawing', 'Fine', 'Flowerscape',
                'Diptych', 'Tonal', 'Texture', 'Traditional', 'Portraiture'
                'Experimental', 'Vanitas', 'Landscape', 'Bay Area', 'Landscapes',
                'Bellases', 'Digital Culture', 'Esoteric', 'Mixedmedia', 'Provocative',
                'Flowers', 'Florals', 'Cats', 'Dogs', 'Cat', 'Dog', 'Horses', 'Horse',
                'Fineart', 'Wildlife', 'Beach Scene', 'Thedoors', 'Fantas<', 'Cityscape',
                'Appropriated', 'Decoration', 'Narrative', 'Cannibalization',
                'Pc Virus History', 'Outsider', 'Material', 'My Own Unique Style',
                'Silver', '3D', 'Diorama', 'Polish', 'Sculpture', 'Digital', 'Prints',
                'Leaves', 'Intuitive', 'Red Felt Inside Box.', 'Brutal', 'Multi Media',
                '3D Sculpture', 'Painting', 'Layering', 'Graphic', 'Wallobject', 'Glitch',
                'Colorful', 'Encaustic', 'Childlike', 'Oakland', 'Dancehall', 'Fine Are',
                'Circles', 'Own Style', 'Nature Inspired', 'Relief', 'Grunge', 'Triptych',
                'Beach', 'Printmaking', 'Caribbean', 'Oversize', 'Tonalist',
                'Interior', 'Sumi Ink', 'Metaphysic', 'Design', 'Stylish', 'Conceptual',
                'Symbolic', 'Lyrical', 'Missoni', 'Fantasy', 'Architectural',
                'Botanical', 'Text', 'Flower', 'Industrial', 'Digital', 'Harmony With Nature',
                'Mixed Media', 'Abstract Wall Sculpture', 'Ink', 'Figuration', 'Tehos',
                'Tutu  Xiaobaitu', 'Hilmaafklint', 'Sussex Landscapes', 'Barbizon',
                'Patterns', 'Pattern', 'Hudson River School', 'Hard Edge Abstraction', 'Floral',
                'Aesthetics', 'Black', 'Fragmented', 'Vertical', 'Illustration', 'Plein Air',
                'Wall Object', 'Topology', 'Prayer', 'Acrylic', 'Shapes', 'Land', 'Freehanddraw',
                'Wall Sculpture', 'Reductive', 'Organic Drawing', 'Digital Collage',
                'Expressive', 'Nature', 'Stylistic', 'Landart', 'Female Form', 'Surf',
                'Aerial', 'Organic', 'Lyrical Abstraction', 'Multicolored', 'Vulumetric',
                'Gilding', 'Unique', 'Scandinavian', 'Architecture', 'Camera Obscura', 'Studio',
                'Portraiture', 'English Contemporary', 'Glossy Finish', 'Contemporary Portrait']

split_list = ['Urban Expressionism', 'Abstract Expressionism']